load("@rules_java//java:defs.bzl", "java_test")

java_test(
    name = "lc",
    srcs = ["Default.java"],
    test_class = "com.lc.test.Default",
    deps = [
        "//src/main/java/com/lc/P283:solution",
    ],
)