load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "ProjectRunner",
    srcs = ["src/main/java/com/ProjectRunner.java"],
    main_class = "com.example.ProjectRunner",
    deps = ["//src/main/java/com/lc/P283:solution",
            "//src/main/java/com/lc/P325:solution"],
)